function u2 = apply_thrust_misalignment(u,angle_rad,axis)
%APPLY_THRUST_MISALIGNMENT Rotate a commanded thrust direction.
%
% 2D:
%   u2 = apply_thrust_misalignment([ur;utheta],angle_rad)
%
% 3D:
%   u2 = apply_thrust_misalignment(u,angle_rad,axis)
% where AXIS is a 3-vector and Rodrigues' rotation formula is used.
%
% This is a deterministic bias model. Random/stochastic pointing errors can
% be generated by the caller and passed as angle_rad histories.

validateattributes(angle_rad,{'numeric'}, ...
    {'scalar','real','finite'});
u=u(:);
if numel(u)==2
    R=[cos(angle_rad) -sin(angle_rad); ...
       sin(angle_rad)  cos(angle_rad)];
    u2=R*u;
elseif numel(u)==3
    if nargin<3 || isempty(axis)
        error('apply_thrust_misalignment:Axis', ...
            'A rotation axis is required for 3D thrust vectors.');
    end
    axis=axis(:);
    if numel(axis)~=3 || ~all(isfinite(axis)) || norm(axis)<eps
        error('apply_thrust_misalignment:Axis', ...
            'axis must be a finite nonzero 3-vector.');
    end
    k=axis/norm(axis);
    u2=u*cos(angle_rad)+cross(k,u)*sin(angle_rad)+ ...
        k*dot(k,u)*(1-cos(angle_rad));
else
    error('apply_thrust_misalignment:Dimension', ...
        'Direction must contain 2 or 3 components.');
end
n=norm(u2);
if n<eps
    error('apply_thrust_misalignment:ZeroDirection', ...
        'Rotated direction has zero norm.');
end
u2=u2/n;
end
