function space = ariane5_2014_reported_design_space()
%ARIANE5_2014_REPORTED_DESIGN_SPACE Reconstruct only unambiguous grids.
%
% Returns parameter vectors directly reconstructible from Table 6.9.
% The 23-point Delta-V path is left as a documented unresolved item rather
% than guessed.

r=ariane5_2014_optimization_reference();
space.core_diameter_m=linspace( ...
    r.search.core_diameter.center_m*(1-r.search.core_diameter.plusminus_fraction), ...
    r.search.core_diameter.center_m*(1+r.search.core_diameter.plusminus_fraction), ...
    r.search.core_diameter.points);
space.stage_thrust_scale=linspace( ...
    1-r.search.stage_thrust.plusminus_fraction, ...
    1+r.search.stage_thrust.plusminus_fraction, ...
    r.search.stage_thrust.points);
space.booster_count=r.search.booster_count_values;
space.booster_burn_fraction=linspace( ...
    r.search.booster_burn_fraction.center-r.search.booster_burn_fraction.plusminus_absolute, ...
    r.search.booster_burn_fraction.center+r.search.booster_burn_fraction.plusminus_absolute, ...
    r.search.booster_burn_fraction.points);
space.booster_diameter_m_reported_center=linspace( ...
    r.search.booster_diameter.center_m*(1-r.search.booster_diameter.plusminus_fraction), ...
    r.search.booster_diameter.center_m*(1+r.search.booster_diameter.plusminus_fraction), ...
    r.search.booster_diameter.points);

% Two interpretations are kept for booster thrust because the thesis tables
% do not make per-booster versus pair-total usage fully explicit.
pair_center=r.original.boosters.thrust_N;
per_booster_center=pair_center/2;
scale=linspace(1-r.search.booster_thrust.plusminus_fraction, ...
    1+r.search.booster_thrust.plusminus_fraction,r.search.booster_thrust.points);
space.booster_thrust_N_pair_interpretation=pair_center*scale;
space.booster_thrust_N_per_booster_interpretation=per_booster_center*scale;

space.delta_v_center=r.search.delta_v_fraction_center;
space.delta_v_plusminus_absolute=r.search.delta_v_plusminus_absolute;
space.delta_v_reported_points=r.search.delta_v_reported_points;
space.delta_v_sequence=[];
space.delta_v_sequence_status='Not reconstructed: exact 23-point path is not specified by thesis text.';
space.reported_total_simulations=r.search.reported_total_simulations;
end
