function print_validation_closure(report)
%PRINT_VALIDATION_CLOSURE Compact console summary for CI and local runs.

fprintf('\n=== Validation Closure v0.9 ===\n');
fprintf('Overall: %s\n',report.overall_status);

v=report.vega;
fprintf(['VEGA: mass table=%s; Kn=5 %.3f s (target %.1f, error %+.3f); ', ...
    'max-q h=%.2f km; full=%s\n'], ...
    v.mass_table.status,v.trajectory.thesis_fixture.kn_time_s, ...
    v.reference.reported.gravity_turn_end_time_s, ...
    v.trajectory.thesis_fixture.kn_time_error_s, ...
    v.trajectory.thesis_fixture.max_q_altitude_m/1000, ...
    v.trajectory.full.status);
if isfield(v.trajectory.full,'total_time_s') && ...
        isfinite(v.trajectory.full.total_time_s)
    fprintf('      total %.3f s; reserve %.2f%%; orbit=%d\n', ...
        v.trajectory.full.total_time_s,v.trajectory.full.reserve_percent, ...
        v.trajectory.full.orbit_reached);
end

p=report.proton;
fprintf(['PROTON: mass table=%s; literal T/W=%.3f; recovered Kn=5 ', ...
    '%.3f s (target %.1f, error %+.3f); full=%s\n'], ...
    p.mass_table.status,p.trajectory.thesis_semantic.liftoff_TW, ...
    p.trajectory.recovered_development.kn_time_s, ...
    p.reference.reported.gravity_turn_end_time_s, ...
    p.trajectory.recovered_development.kn_time_error_s, ...
    p.trajectory.full.status);

a=report.ariane5;
fprintf(['ARIANE 5: mass table=%s; geometry table=%s; ', ...
    'modern original GLOW=%.1f kg; modern optimum GLOW=%.1f kg; ', ...
    'modern reduction=%.2f%%; trajectory=%s\n'], ...
    a.mass_table.status,a.geometry_table.status, ...
    a.modern_benchmark.modern_original_GLOW_kg, ...
    a.modern_benchmark.modern_optimum_GLOW_kg, ...
    a.modern_benchmark.modern_reduction_percent,a.trajectory.status);
fprintf('          exact historical 23-point Delta-V sequence available=%d\n', ...
    a.design_space.exact_delta_v_sequence_available);
fprintf('Closure classified=%d\n\n',report.validation_closure_complete);
end
